### ISSUE TITLE
cURL example for GET /calendar/{toidentity}/list

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/docs#10]
# What is the problem?

cURL code example missing for [/calendar/{toidentity}/list](https://docs.oftrust.net/?shell#calendar-toidentity-list)

# What do you expect to see / happen? 

- Provide cURL code example (with headers) which uses the endpoint and is using sandbox domain. 
- provide sample JSON response with headers. 

See this file to understan structure of the expected result: https://github.com/PlatformOfTrust/docs/blob/master/raml2markdown/examples/GET_calendar_id.example

- at this point don't worry about the `java`, `javascript`, `python` examples in the file. 
- store example file to raml2markdown/examples/GET_calendar_toidentity_list.example

**Comment by soderluk** [comment]
@kyyberi: The example is the `calendar-list.curl` example:
`curl -X PUT https://api-sandbox.oftrust.net/calendar/v1/calendar/34fe0b13-e031-4ef2-822e-17eabad63259/list` which is apparently wrong anyway. I'll fix the request and remove the `curl -X PUT`
