### ISSUE TITLE
Missing submodule URL

### ISSUE THREAD

**Issue by soderluk** [PlatformOfTrust/docs#19]
# What is the problem?
When cloning the repository in GitKraken, the submodule `raml2markdown/oas-raml-converter` URL is missing. GitKraken shows big red boxes with errors about the URL missing to the submodule.

# What do you expect to see / happen? 
Expected to be able to clone the repository and initialize the submodule without errors.

**Comment by kyyberi** [comment]
I have no idea how to add meta information for submodule, so that it's in commits: 
```
more raml2markdown/oas-raml-converter/.git/config 

[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        ignorecase = true
        precomposeunicode = true
[remote "origin"]
        url = git@github.com:mulesoft/oas-raml-converter.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

**Comment by soderluk** [comment]
Check out the `.gitmodules` file: https://git-scm.com/docs/gitmodules

**Comment by kyyberi** [comment]
Added https://github.com/PlatformOfTrust/docs/blob/master/.gitmodules 

hope that helps.

**Comment by soderluk** [comment]
Bueno. Works now.
