### ISSUE TITLE
Broker API version number

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/docs#37]
# What is the problem?

https://docs.oftrust.net/#broker-api Broker API versioning is not consistent with rest of the APIs. We have only major number eg /v1/ /v2/. 

<img width="717" alt="Näyttökuva 2019-3-27 kello 11 01 37" src="https://user-images.githubusercontent.com/1927158/55063274-52669000-5080-11e9-8ae2-82d8ff63a708.png">

# What do you expect to see / happen? 

Change the versioning in 
* Broker API routing to `/broker/v1/fetch-data-product`
* and in code example https://github.com/PlatformOfTrust/docs/blob/master/raml2markdown/examples/POST_fetch-data-product.example)

**Comment by soderluk** [comment]
Are we at `v1` yet @lietu ?

**Comment by lietu** [comment]
That's a good question, we did skip some parts of the v1.0 plan, however those don't seem like things that affect the API - namely requiring valid `@context` from responses and valid SSL certificate from translators.

Without an actual thorough check I would say that the answer is approximately yes 😄

**Comment by soderluk** [comment]
I'd maybe move it to `v1` because the signing and validation of tokens is there already, and the validation of the context and SSL is not a breaking change which can be added whenever.

**Comment by soderluk** [comment]
Closed by #43
