### ISSUE TITLE
Correct time format in docs

### ISSUE THREAD

**Issue by lietu** [PlatformOfTrust/docs#4]
The docs incorrectly claim we use [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) when we actually use only a subset of it - [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt).

There *may* however in the future be some parts where we will use ISO-8601 or other standards for e.g. time intervals in calendar events or some such.

**Comment by kyyberi** [comment]
Fixed in https://github.com/PlatformOfTrust/docs/commit/bc4344167c5f360e0e93e918f803517d972a5404
