### ISSUE TITLE
Endpoint usage details missing from Description field

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/docs#52]
# What is the problem?

Currently the middle section in API Docs is extremely limited and does not contain the needed information (explanations) of how to use the endpoint. 

Currently the code example column contains some information, but all that should not be there in most cases.

<img width="1546" alt="Näyttökuva 2019-4-6 kello 11 43 13" src="https://user-images.githubusercontent.com/1927158/55667185-9ec08580-5861-11e9-843b-b677c012d344.png">
 

# What do you expect to see / happen? 

* Check if info is lost in transformation from RAML -> OAS -> Slate md
* If not the above, then add more details to RAML source files.

**Comment by soderluk** [comment]
Fixed in #57
