### ISSUE TITLE
Mismatch between Identities API query param description and endpoint path

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/docs#54]
# What is the problem?

Query param description does not match the endpoint path. Should be `GET /identities/{version}/?type=Ap

<img width="705" alt="Näyttökuva 2019-4-7 kello 15 20 57" src="https://user-images.githubusercontent.com/1927158/55683457-cc342e80-5948-11e9-91d2-56da9625468a.png">

# What do you expect to see / happen?

**Comment by soderluk** [comment]
Fixed in #57
