### ISSUE TITLE
Broken / outdated links in docs.oftrust.net

### ISSUE THREAD

**Issue by developers-sbp** [PlatformOfTrust/docs#80]
# What is the problem?

Recorded a couple of broken links in docs.oftrust.net, which I'm listing below:

* https://docs.oftrust.net/#authentication , the "App development guide" URL (https://developer.oftrust.net/guides/build-apps ) is broken (404)

* https://docs.oftrust.net/#authentication-code-example , the "sandbox" URL (https://developer.oftrust.net/guides/sandbox ) is broken (I'm assuming this should be https://world-sandbox.oftrust.net/ )

# What do you expect to see / happen? 

The links should be directing users to the corresponding resources.

**Comment by kyyberi** [comment]
Thanks! We'll add this to tasks list of future sprints.

**Comment by kyyberi** [comment]
All of the examples are working and point to correct locations in Developer Portal. 
For example Sandbox link should and does link to description of the sandbox. That is more than sandbox version of World
