### ISSUE TITLE
Branded icons for Open API, RAML and Insomnia

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/docs#87]
# What is the problem?

API Docs provides links to Open API Spec & RAML files for each API as resources. Before launch Insomnia package is offered as well. 
Each of the resources are linked to the API docs in right-most column

<img width="796" alt="Näyttökuva 2019-5-18 kello 13 25 57" src="https://user-images.githubusercontent.com/1927158/57968279-b450c100-7970-11e9-829b-694ce54fa0f3.png">

Plain links are good, but Platform of Trust branded icons for: 
* OpenAPI
* RAML 
* Insomnia

Would make it better. 

# What do you expect to see / happen? 

Provide branded icons for:
* RAML
* OpenAPI
* Insomnia

## Acceptance criteria

- [x] Icons for RAML, OpenAPI and Insomnia are created
- [x] PR containing mentioned icons (as svg) in folder `build/images/` is created
- [x] PO reviews and accepts the icons

**Comment by Nazarah** [comment]
@kyyberi 
Here are 2 styles of resource links that has been designed.
1. [1st link](https://codepen.io/nazarah/pen/MdQbxm) shows brand icons within buttons with three different hover effects.
2. [2nd link](https://codepen.io/nazarah/pen/XwENgK?editors=1100) shows brand icons themselves as button, in **small**, **medium** and **large size**. Here 2 different hover effects have been used.

Let me know which style/size/hover-effect you prefer.

**Comment by Nazarah** [comment]
after getting feedback from @kyyberi , here is the newer version of button for the resources.
https://codepen.io/nazarah/pen/pmLpwZ
Buttons for Insomania and RAML will be added soon.
![HexButton](https://user-images.githubusercontent.com/17976243/58329800-13fe0f00-7e3e-11e9-8e83-44b2a094dcc6.gif)
