### ISSUE TITLE
Design Getting started section layout

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/docs#92]
# What is the problem?

Current version of the Getting started section in API Docs is not visually appealing. It's just a list of items. Furthermore it does not clearly enough imply how to get started. 
<img width="741" alt="Näyttökuva 2019-5-28 kello 8 28 48" src="https://user-images.githubusercontent.com/1927158/58453154-a9412200-8122-11e9-95ad-e06b5f13f16a.png">

# What do you expect to see / happen? 

Step like structure and call for actions as buttons. Revisit the texts together with PO. Reviews from PO, UX lead and Tech support (Jaro).  Review request marked in Github and if no review is done in 5 days, it's the same as acceptance. 

# Acceptance citeria

- [x] Design drafts (screenshots) added to the issue
- [x] PO review
- [x] UX lead review

**Comment by Nazarah** [comment]
### Mobile View

Instructions to get started come as boxes marked with 1,2 and 3.
Each box contains CTA button to perform the mentioned action.
**Question:** To get Bearer Token, should CTA navigate user the the bearer token section in API Docs? Or to the Sandbox environment.

![Mobile1](https://user-images.githubusercontent.com/17976243/59674740-bb742480-91e5-11e9-8df2-64f95e55b141.png)

Tips for beginners to start using API Docs appear below the Getting Started Section.
Each Tip appear with a light bulb bullet point.
Below the tip appears a section allowing users to contact using Email or GitHub Issue (related icons are hyperlinked with specific actions)

![Mobile2](https://user-images.githubusercontent.com/17976243/59674939-0f7f0900-91e6-11e9-901e-06d7c89b15d5.png)

**Comment by Nazarah** [comment]
### Desktop View

![Desktop](https://user-images.githubusercontent.com/17976243/59674981-245b9c80-91e6-11e9-917c-a426cf4e33cb.png)

Tips for beginners and Contact section appears on the rightmost pane in desktop view.

**Comment by kyyberi** [comment]
Excellent work! I was just thinking that we probably should replace the "Get familiar with ontologies" with "Try out APIs - use provided code examples" or alike. The ontologies part is discussed anyway in the below "Standards used" section. 

Furthermore, would it be a bad idea to add a text below the boxes that invites the user to take a look at the guides provided in the developer portal. Guides provide practical examples of how the APIs are used to create digital twins, data products and identities (while still using the standard ontology.

**Comment by kyyberi** [comment]
Ready for implementation, just take the above comments into account.

**Comment by Nazarah** [comment]
### Wireframe version 2 

(changes suggested above are added here)

**1. Mobile View**

a. Clicking Try Our APIs navigates user to the **Identity/Production** APIs section in the same page. Shows the **POST HTTP request codes** for the above API
**N.B.** Should we consider navigating to the runkit example code that is to be developed in Developer Portal later on?

b. Clicking on [Our Guides](https://developer.oftrust.net/guides) navigates the user to the Guides page in Developers Portal.

![Mobile1](https://user-images.githubusercontent.com/17976243/59818502-05741c00-9346-11e9-906b-7f4b0b9b9c8c.png)


**2. Desktop View**

![Desktop](https://user-images.githubusercontent.com/17976243/59818513-0d33c080-9346-11e9-84b2-24e9824d077c.png)

**Comment by kyyberi** [comment]
With the "Try out APIs - use provided code examples"  I was referring to code examples provided in the API docs. But jumping to Developer portal also from here (guides link below is another jump) is an option.

**Comment by Nazarah** [comment]
In any case, the runkit examples for Developer Portal is still to be implemented. For the time being, we can use the code examples provided in API Docs. In future, we can always decide whether to go for the jump to runkit or stay in this page. :)

**Comment by kyyberi** [comment]
At some point code examples given here should be runnable as well. That is a major epic and probably not happening this year.
